[theme.overrides]
idle_bg = "#101010"
idle_fg = "#c4b59c"
separator_bg = "#101010"
separator_fg = "#a19278"
separator = " | "
warning_bg = "#101010"
good_bg = "#101010"

[[block]]
block = "net"
format = "net up"
inactive_format = "net down"
missing_format = "net down"

[[block]]
block = "sound"
format = "vol $volume"
max_vol = 150
show_volume_when_muted = true

[[block]]
block = "time"
format = "$timestamp.datetime(f:'%a %d, %I:%M') "
