[colors.primary]
background = '#120e08'
foreground = '#a68d6a'

[colors.normal]
black   = '#120e08'
white   = '#a68d6a'
red     = '#d6be9c'
green   = '#c3a881'
blue    = '#a68d6a'
yellow  = '#c3a881'
cyan    = '#816c4e'
magenta = '#816c4e'

[colors.bright]
black   = '#493b2d'
white   = '#d6be9c'
red     = '#d6be9c'
green   = '#c3a881'
blue    = '#a68d6a'
yellow  = '#c3a881'
cyan    = '#816c4e'
magenta = '#816c4e'

[font]
size = 16

[font.normal]
family = "fira code"
style = "medium"

[terminal.shell]
program = "/bin/fish"

[window.padding]
x = 24
y = 24
